backend:
  name: git-gateway
  branch: master
slug:
  encoding: 'ascii'
  clean_accents: true
  sanitize_replacement: '_'
media_folder: 'static/uploads'
public_folder: '/uploads'
site_url: https://remedium.ml
display_url: https://remedium.ml
logo_url: https://remedium.ml/logo-Remedium.jpg
# publish_mode: editorial_workflow
collections:
  - name: 'posts'
    label: 'Posts'
    folder: 'src/posts'
    create: true
    slug: '{{year}}-{{month}}-{{day}}_{{slug}}'
    fields:
      - { label: 'Title', name: 'title', widget: 'string', required: true }
      - { label: 'Publish Date', name: 'date', widget: 'datetime', required: true }
      - { label: 'Featured Image', name: 'thumbnail', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown', required: true }
